Add exit code to simtests when failing

diff --git a/.github/workflows/simtest.yml b/.github/workflows/simtest.yml
--- a/.github/workflows/simtest.yml
+++ b/.github/workflows/simtest.yml
@@ -57,6 +57,9 @@ jobs:
             echo "Received the following output:"
             echo "-----"
             echo "$RESULT"
+            exit 1
           else
             echo "Tests passed."
           fi
+
+# TODO: Failing test still passes
